baseURL = 'https://navdeep-singh-ghotra.github.io/navdeep-singh-ghotra.github.io/'
languageCode = 'en-us'
title = 'Navdeep Singh Ghotra'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Navdeep"
weight = 1
contentDir = "content/"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.fr]
title = "Ananke Fr"
weight = 2
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "dark-green"
author = "NSG"
favicon = ""
site_logo = "/cloud.jpg"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-lightest-blue"
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"