baseURL = 'https://navdeep-singh-ghotra.github.io/'
languageCode = 'en-us'
title = ''
theme = 'ananke'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'