{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: {{ .Values.gateway.listener.port }}
      protocol: {{ .Values.gateway.listener.protocol }}
      allowedRoutes:
        namespaces:
          from: All
{{- end }}